# Generated by Django 3.2.20 on 2023-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='size',
            field=models.CharField(choices=[('S', 'Chico (100g-200g)'), ('M', 'Mediano (200g-350g)'), ('L', 'Grande (350g-500g)')], default='M', max_length=2),
        ),
    ]
