# Generated by Django 4.1 on 2023-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trash", "0002_alter_trash_options_trash_start_date_formated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trash",
            name="on_process",
            field=models.BooleanField(default=False),
        ),
    ]
