# Generated by Django 4.1 on 2023-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trash", "0004_auto_20230905_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="trash",
            name="processed_size",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
