# Generated by Django 4.1 on 2023-08-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Food",
        ),
    ]
