# Generated by Django 3.2.20 on 2023-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_name_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name_eng',
            field=models.CharField(max_length=255),
        ),
    ]
