# Generated by Django 3.2.20 on 2023-09-25 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='food_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_eng',
            field=models.CharField(max_length=255, verbose_name='Nombre Ingles'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.IntegerField(verbose_name='Peso'),
        ),
    ]
