# Generated by Django 3.2.20 on 2023-09-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_trash_on_process'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='processes',
            field=models.ManyToManyField(related_name='process', to='trash.Trash'),
        ),
    ]
